# Keras Basics

Welcome to the section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

This means we should get familiar with some Keras fundamentals and basics!

## Imports


In [34]:
import numpy as np
from numpy import genfromtxt
import warnings

# Ignore all warnings (use with caution)
warnings.filterwarnings("ignore")

## Dataset

We will use the Bank Authentication Data Set to start off with. This data set consists of various image features derived from images that had 400 x 400 pixels. You should note **the data itself that we will be using ARE NOT ACTUAL IMAGES**, they are **features** of images. In the next lecture we will cover grabbing and working with image data with Keras. This notebook focuses on learning the basics of building a neural network with Keras.

_____
More info on the data set:

https://archive.ics.uci.edu/ml/datasets/banknote+authentication

Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization, an industrial camera usually used for print inspection was used. The final images have 400x 400 pixels. Due to the object lens and distance to the investigated object gray-scale pictures with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images.


Attribute Information:

1. variance of Wavelet Transformed image (continuous) 
2. skewness of Wavelet Transformed image (continuous) 
3. curtosis of Wavelet Transformed image (continuous) 
4. entropy of image (continuous) 
5. class (integer) 

## Reading in the Data Set

We've already downloaded the dataset, its in the DATA folder. So let's open it up. 

In [35]:
import numpy as np
from numpy import genfromtxt

In [36]:
data = genfromtxt("C:/Users/bobby/Downloads/Computer-Vision-with-Python/DATA/bank_note_data.txt",delimiter=",")

In [37]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [38]:
labels = data[:,4] ### this are my classes 

In [39]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [40]:
features = data[:,0:4] ##this are my features

In [41]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [42]:
X = features
y = labels

## Split the Data into Training and Test

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now. **Remember to check out the video explanation as to why we split and what all the parameters mean!**

In [43]:
### for splititng the training and test model
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [45]:
len(X_train)

919

In [46]:
len(X)

1372

In [47]:
len(X_test)

453

In [48]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [49]:
len(y_train)

919

In [50]:
len(y_test)

453

In [51]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [52]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [53]:
## standardization of data

from sklearn.preprocessing import MinMaxScaler

In [54]:
scaler_object =  MinMaxScaler()

In [55]:
scaler_object.fit(X_train)

MinMaxScaler()

In [56]:
scaled_X_train = scaler_object.transform(X_train)

In [57]:
scaled_X_test = scaler_object.transform(X_test)

In [58]:
scaled_X_train.max()

1.0000000000000002

In [59]:
scaled_X_train.min()

0.0

## Building the Network with Keras

Let's build a simple neural network!

In [60]:
### building a simple network with keras
from keras.models import Sequential
from keras.layers import Dense

In [61]:
## creats model
model = Sequential()



## adds layers
## input layer
model.add(Dense(4,input_dim=4,activation="relu"))

##hidden layer
model.add(Dense(8,activation="relu"))

## output layer
model.add(Dense(1,activation="sigmoid"))

### Compile Model

In [62]:
### compile the model
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

## Fit (Train) the Model

In [65]:
## train the model

model.fit(scaled_X_train,y_train,epochs=80,verbose=2)

Epoch 1/80
29/29 - 0s - loss: 0.0321 - accuracy: 0.9848 - 28ms/epoch - 967us/step
Epoch 2/80
29/29 - 0s - loss: 0.0336 - accuracy: 0.9859 - 25ms/epoch - 878us/step
Epoch 3/80
29/29 - 0s - loss: 0.0321 - accuracy: 0.9880 - 23ms/epoch - 796us/step
Epoch 4/80
29/29 - 0s - loss: 0.0317 - accuracy: 0.9837 - 28ms/epoch - 955us/step
Epoch 5/80
29/29 - 0s - loss: 0.0316 - accuracy: 0.9837 - 24ms/epoch - 838us/step
Epoch 6/80
29/29 - 0s - loss: 0.0312 - accuracy: 0.9902 - 28ms/epoch - 956us/step
Epoch 7/80
29/29 - 0s - loss: 0.0318 - accuracy: 0.9837 - 28ms/epoch - 975us/step
Epoch 8/80
29/29 - 0s - loss: 0.0309 - accuracy: 0.9913 - 28ms/epoch - 975us/step
Epoch 9/80
29/29 - 0s - loss: 0.0310 - accuracy: 0.9902 - 29ms/epoch - 989us/step
Epoch 10/80
29/29 - 0s - loss: 0.0315 - accuracy: 0.9837 - 30ms/epoch - 1ms/step
Epoch 11/80
29/29 - 0s - loss: 0.0307 - accuracy: 0.9880 - 27ms/epoch - 926us/step
Epoch 12/80
29/29 - 0s - loss: 0.0304 - accuracy: 0.9837 - 27ms/epoch - 928us/step
Epoch 13/80
29/

## Predicting New Unseen Data

Let's see how we did by predicting on **new data**. Remember, our model has **never** seen the test data that we scaled previously! This process is the exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed .

In [66]:
##prediction of model on test data
from sklearn.metrics import confusion_matrix,classification_report

In [67]:
prediction = model.predict(scaled_X_test)

15/15 [==============================] - 0s 2ms/step


In [68]:
# Convert probability predictions to class labels

prediction_classes =  np.argsort(prediction, axis=-1)

## Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!

In [69]:
model.metrics_names

['loss', 'accuracy']

In [70]:
from sklearn.metrics import confusion_matrix,classification_report

In [71]:
prediction = model.predict(scaled_X_test)

15/15 [==============================] - 0s 751us/step


In [72]:
confusion_matrix(y_test, prediction_classes)

array([[257,   0],
       [196,   0]], dtype=int64)

In [73]:
print(classification_report(y_test,prediction_classes))

              precision    recall  f1-score   support

         0.0       0.57      1.00      0.72       257
         1.0       0.00      0.00      0.00       196

    accuracy                           0.57       453
   macro avg       0.28      0.50      0.36       453
weighted avg       0.32      0.57      0.41       453



## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [74]:
### saving the model

model.save("mysupermodel.h5")

In [75]:
from keras.models import load_model

In [76]:
newmodel= load_model("mysupermodel.h5")

In [78]:
newmodel.predict(scaled_X_test)

15/15 [==============================] - 0s 744us/step


array([[4.78097127e-06],
       [3.49479504e-02],
       [8.81477911e-03],
       [1.10911147e-08],
       [1.15981959e-06],
       [7.10971608e-06],
       [3.03939009e-06],
       [1.54312190e-07],
       [2.25313829e-06],
       [4.25976793e-07],
       [8.34817350e-01],
       [9.98539031e-01],
       [3.08147605e-06],
       [9.91914451e-01],
       [1.63674940e-05],
       [7.45653212e-01],
       [9.94523346e-01],
       [9.95943606e-01],
       [9.32354212e-01],
       [8.62678051e-01],
       [6.06920764e-07],
       [6.93398249e-07],
       [9.34134543e-01],
       [8.18795911e-08],
       [9.99522746e-01],
       [2.44424882e-07],
       [1.58538409e-08],
       [9.96140420e-01],
       [2.39867542e-10],
       [1.36786182e-09],
       [9.97907639e-01],
       [3.68038900e-06],
       [4.61960663e-05],
       [9.99352038e-01],
       [9.99241829e-01],
       [3.76028630e-08],
       [7.41163313e-01],
       [9.97127831e-01],
       [9.98694539e-01],
       [1.25929751e-06],
